apiVersion : apps/v1
kind: Deployment
metadata:
  name: apicontainer 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicontainer
  template:
    metadata:
      labels:
        app: apicontainer 
    spec:
      containers:
        - name: apicontainer 
          image: dat158.azurecr.io/apicontainer
          ports:
          - containerPort: 80